---
# pvc.yml path
pvc_yml: './roles/rbd_ceph_performance/templates/pvc.yml'
# kubeconfig path
kubeconfig: '$HOME/.kube/config'
# ocs namespace
name_space: 'testing-ocs-storage'
# postgres namespace base
pgbench_project: 'my-testing-pgbench-ocs-'
# pgbench options it will run 16 clients, 16 threads for 300 secs
pgbench_options: ' -c 16 -j 16 -P 30 -T 300 sampledb'
# ocs ceph block provisioner
rbd_provisioner: 'openshift-storage.rbd.csi.ceph.com'
# ocs ceph file provisioner
cephfs_provisioner: 'openshift-storage.cephfs.csi.ceph.com'
# machineset project
machineset_project: 'openshift-machine-api'
# default instance
oldinstancetype: 'm5.4xlarge'
# new instance
instancetype: 'm5.4xlarge'
# ebs size
ebs_size: 4096
osds_total: 16
partitions_total: 4
# home directory
home_user: "{{ ansible_env.HOME }}"
# zones
# zone_1: 'odf-az1'
# zone_2: 'odf-az2 '
# arbiter: 'arbiter-az3'
zone_1: 'datacenter1'
zone_2: 'datacenter2'
arbiter: 'arbiter'
# Bare metal AWS instance
bm_instance: 'c5d.metal'