apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: ocs-storagecluster-ceph-rgw
# Change "rook-ceph" provisioner prefix to match the operator namespace if needed
provisioner: openshift-storage.ceph.rook.io/bucket
reclaimPolicy: Delete
parameters:
  objectStoreName: s3a
  objectStoreNamespace: openshift-storage
  region: eu-west-1