apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  name: ocs-storagecluster
  namespace: openshift-storage
spec:
  arbiter:
    enable: true  # <-- Enable arbiter mode for Metro Dr stretch cluster
  nodeTopologies:
    arbiterLocation: arbiter  # <-- Modify to label for arbiter zone
  manageNodes: false
  resources: {}
  monDataDirHostPath: /var/lib/rook
  managedResources:
    cephBlockPools:
      reconcileStrategy: manage
    cephFilesystems:
      reconcileStrategy: manage
    cephObjectStoreUsers:
      reconcileStrategy: manage
    cephObjectStores:
      reconcileStrategy: manage
    snapshotClasses:
      reconcileStrategy: manage
    storageClasses:
      reconcileStrategy: manage
  multiCloudGateway:
    reconcileStrategy: manage
  storageDeviceSets:
  - count: 2  # <-- For each set of 4 disks increment the count by 1
    dataPVCTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: '1'  # <-- Use value smaller than actual disk size
        storageClassName: localblock  # <-- Modify to correct LSO storageclass
        volumeMode: Block
    name: ocs-deviceset
    placement: {}
    portable: false
    replica: 4  # <-- Replica = 4 for volume and object storage
    resources: {}