- pause:
    prompt: |
          Valid I/O type (Only one option is available):
          - read
          - write
          - randwrite
          - randread
          - readwrite
          - randrw
  register: io_type
- pause:
    prompt: |
          Valid I/O size in KB example:
          - 4, 8, 16, 32, 64, 128, 256, 1024, 2048, 4096 ?
  register: io_size
- pause:
    prompt: |
          Valid io_threads example:
          - 1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096
  register: io_threads
- pause:
    prompt: |
          IO in GB total in GB (max 100):
  register: io_total
- pause:
    prompt: |
          IO rw_mix_read:
  register: rwmixread
  when: io_type.user_input == "readwrite" or io_type.user_input == "randrw"
- pause:
    prompt: |
          IO rwmixwrite:
  register: rwmixwrite
  when: io_type.user_input == "readwrite" or io_type.user_input == "randrw"