---
- pause:
    prompt: |
          ###########################################################################################
          # The playbook automate the following taks:                                               #
          # - Create project: testing-ocs-storage                                                   #
          # - Deploy fio-performance-testing statefulset                                            #
          # - Scale the statefulset to a number of pods based on user INPUT                         #
          # - Testing the workload profiles based on fio interactive INPUT                          #
          # - When the benchmark is finished it takes care to clean the test environment            #
          ###########################################################################################

          ###########################################################################################
          # Select the task number:                                                                 #
          # 1 -> FIO: Running fio workload profile based on user INPUT                              #
          # 2 -> POSTGRES: Running pgbench on a number of DBs based on user INPUT                   #
          # 3 -> S3CMD: Data ingestion on cephfs pvc then s3cmd sync to MCG buckets                 #
          # 4 -> PVC CREATE: Create an INPUT number of pvcs based on user INPUT                     #
          # 5 -> PARTITION OSDs on nodes with label: cluster.ocs.openshift.io/openshift-storage=    #
          # 6 -> DEPLOY STRETCHED CLUSTER VMs: 3 AZs, Replica-4 (2 OSD nodes in 2 AZ + arbiter)     #
          # 7 -> Install ODF v4.7 RC operator (tag latest-4.7)                                          #
          # 8 -> HA TEST STRETCHED CLUSTER (requires ODF v4.7 and aws cli)                          #
          ###########################################################################################
  register: benchmark

- name: Fio testing
  include_tasks: deploy_test_env.yml
  when: benchmark.user_input == "1"

- name: Postgres pgbench testing
  include_tasks: pgbench.yml
  when: benchmark.user_input == "2"

- name: s3cmd testing
  include_tasks: s3cmd.yml
  when: benchmark.user_input == "3"

- name: pvc testing
  include_tasks: lets_create_pvc.yml
  when: benchmark.user_input == "4"

- name: OSD partitoning
  include_tasks: partitioning.yml
  when: benchmark.user_input == "5"

- name: Infra stretched cluster deployment
  include_tasks: prepare-machinesets-stretched.yaml
  when: benchmark.user_input == "6"

- name: Install ODF v4.7
  include_tasks: enable-odfv47.yml
  when: benchmark.user_input == "7"

- name: HA test stretched cluster
  include_tasks: ha_test.yml
  when: benchmark.user_input == "8"