---
- pause:
    prompt: |
          #################################################################################
          # The playbook automate the following taks:                                     #
          # - Create project: testing-ocs-storage                                         #
          # - Deploy fio-performance-testing statefulset                                  #
          # - Scale the statefulset to a number of pods based on user INPUT               #
          # - Testing the workload profiles based on fio interactive INPUT                #
          # - When the benchmark is finished it takes care to clean the test environment  #
          #################################################################################
          
          Select the task number:
              1 -> FIO: Running synthetic becnhmark fio workload profile based on user INPUT
              2 -> POSTGRES: Running pgbench on number of DB instances based on user INPUT
              3 -> s3cmd: Create a number of fio instances with cephfs pvc, mount from s3cmd pod and sync objects in MCG buckets
              4 -> pvc: Create an INPUT number of pvcs and loop for a number of pvs based on user INPUT
  register: benchmark

- name: Fio testing
  include_tasks: deploy_test_env.yml
  when: benchmark.user_input == "1"

- name: Postgres pgbench testing
  include_tasks: pgbench.yml
  when: benchmark.user_input == "2"

- name: s3cmd testing
  include_tasks: s3cmd.yml
  when: benchmark.user_input == "3"

- name: pvc testing
  include_tasks: lets_create_pvc.yml
  when: benchmark.user_input == "4"