---
- pause:
    prompt: |
          Select the task number:
              - 1 -> Deploy fio statefulset, replicas in project=testing-ocs-storage, testing and cleaning the environment
              - 2 -> Running postgres pgbench from Template, testing and cleaning the environment
  register: benchmark

- name: Fio testing
  include_tasks: deploy_test_env.yml
  when: benchmark.user_input == "1"

- name: Postgres pgbench testing
  include_tasks: pgbench.yml
  when: benchmark.user_input == "2"


#- name: s3cmd testing
#  include_tasks: s3cmd.yml
#  when: benchmark.user_input == "4"

#- name: s3cmd delete
#  include_tasks: s3cmd-delete.yml
#  when: benchmark.user_input == "5"
