---
- pause:
    prompt: |
          Can you tell me what kind of benchmark would you like to run? :
              - deploy_environment
              - fio
              - clean-fio-tests
              - s3cmd-sync
              - s3cmd-delete
              - rbd-bench
              - delete-fio-pods
  register: benchmark

- name: create environment test
  include_tasks: deploy_test_env.yml
  when: benchmark.user_input == "deploy_environment"

- name: clean-fio-tests
  include_tasks: clean-fio-test.yml
  when: benchmark.user_input == "clean-fio-tests"

- name: fio benchmark
  include_tasks: fio-tests.yml
  when: benchmark.user_input == "fio"

- name: Ceph rbd bench
  include_tasks: rbdbench-tests.yml
  when: benchmark.user_input == "rbd-bench"

- name: s3cmd testing
  include_tasks: s3cmd.yml
  when: benchmark.user_input == "s3cmd-sync"

- name: s3cmd testing
  include_tasks: s3cmd-delete.yml
  when: benchmark.user_input == "s3cmd-delete"
