---
- pause:
    prompt: |
          Select the task number:
              - 1 -> deploy fio file and block statefulset and pods (project=testing-ocs-storage)
              - 2 -> fio workloads
              - 3 -> clean-fio-tests
              - 6 -> delete-fio-pods
  register: benchmark

- name: create environment test
  include_tasks: deploy_test_env.yml
  when: benchmark.user_input == "1"

- name: fio benchmark
  include_tasks: fio-tests.yml
  when: benchmark.user_input == "2"

- name: clean-fio-test
  include_tasks: clean-fio-test.yml
  when: benchmark.user_input == "3"

- name: s3cmd testing
  include_tasks: s3cmd.yml
  when: benchmark.user_input == "4"

- name: s3cmd delete
  include_tasks: s3cmd-delete.yml
  when: benchmark.user_input == "5"

- name: fio delete environment test
  include_tasks: fio-delete.yml
  when: benchmark.user_input == "6"
