---
- pause:
    prompt: |
          ###########################################################################################
          # Tasks 1,3,4 the playbook automate the following taks:                                   #
          #   - Create project: testing-ocs-storage                                                 #
          # Task 1:                                                                                 #
          #   - Deploy fio-performance-testing statefulset                                          #
          #   - Scale the statefulset to a number of pods based on user INPUT                       #
          #   - Testing the workload profiles based on fio interactive INPUT                        #
          #   - When the benchmark is finished it takes care to clean the test environment          #
          # Task 2:                                                                                 #
          #   - Create pgbench #namespaces based on user input                                      #
          #   - Initialize DB sampledb on each pgbench project                                      #
          #   - Running pgbench in parallel in all the previous created DBs                         #
          # Task 3:                                                                                 #
          #   - Similar to task 1 but the pod has 2 containers: fio and s3cmd:                      #
          #     - fio: used for ingestion with a cephfs pvc                                         #
          #     - s3cmd: used for s3cmd sync, based on previous ingestion of objects                #
          # Task 4:                                                                                 #
          #   - It will create a number of pvcs on ODF based on user input                          #
          #   - pvcs will be deleted at the end of the test                                         #
          # Task 5 is used when you need to create 2 partitions disk on OCS labeled nodes           #
          # Task 6 is to fully automate ODF cluster based on:                                       #
          #   - LSO Opearator for local storage with auto-discovery                                 #
          #   - ODF v4.7.0 Operator (from Official openshift OperatorHub)                           #
          #   - 3 AZ: datacenter1, datacenter2, arbiter                                             #
          #     - datacenter1: 2 OSD nodes with 4TB partitioned in 2x2TB                            #
          #     - datacenter2: 2 OSD nodes with 4TB partitioned in 2x2TB                            #
          #     - arbiter: 1 node as arbiter for ODF Metro Cluster                                  #
          #     - Deploy ODF v4.7.0 cluster by using CR on the provisioned infrastrcture            #
          ###########################################################################################

          ###########################################################################################
          # Select the task number:                                                                 #
          # 1 -> FIO: Running fio workload profile based on user INPUT                              #
          # 2 -> POSTGRES: Running pgbench on a number of DBs based on user INPUT                   #
          # 3 -> S3CMD: Data ingestion on cephfs pvc then s3cmd sync to MCG buckets                 #
          # 4 -> PVC CREATE: Create an INPUT number of pvcs based on user INPUT                     #
          # 5 -> PARTITION OSDs on nodes with label: cluster.ocs.openshift.io/openshift-storage=    #
          # 6 -> Deploy ODF v4.7.0 cluster based on 2 AZ each with nodes + 1 AZ with arbiter node)  #
          # 7 -> HA TEST STRETCHED CLUSTER (requires ODF v4.7 and aws cli)                          #
          ###########################################################################################
  register: benchmark

- name: Fio testing
  include_tasks: deploy_test_env.yml
  when: benchmark.user_input == "1"

- name: Postgres pgbench testing
  include_tasks: pgbench.yml
  when: benchmark.user_input == "2"

- name: s3cmd testing
  include_tasks: s3cmd.yml
  when: benchmark.user_input == "3"

- name: pvc testing
  include_tasks: lets_create_pvc.yml
  when: benchmark.user_input == "4"

- name: OSD partitoning
  include_tasks: partitioning.yml
  when: benchmark.user_input == "5"

- name: Infra stretched cluster deployment
  include_tasks: prepare-machinesets-stretched.yaml
  when: benchmark.user_input == "6"

- name: HA test stretched cluster
  include_tasks: ha_test.yml
  when: benchmark.user_input == "7"