- pause:
    prompt: |
          Can you tell me what kind of benchmark would you like to run? :
              - fio
              - rbd-bench
              - clean-fio-tests
              - delete-fio-pods
  register: benchmark

- name: clean-fio-tests
  include_tasks: clean-fio-tests.yml
  when: benchmark.user_input == "clean-fio-tests"

- name: fio benchmark
  include_tasks: fio-tests.yml
  when: benchmark.user_input == "fio"

- name: Ceph rbd bench
  include_tasks: rbdbench-tests.yml
  when: benchmark.user_input == "rbd-bench"
