- pause:
    prompt: |
          How many pg DBs to deploy?:
          - 4, 8, 16?
  register: db_instances
- pause:
    prompt: |
          What's the scaling option? The amount of capacity will be "scaling_option x 16MB" 
          - 50, 100, 500, 1000, 5000?
  register: scaling_option

- name: Create the postgres namespace and DB instance
  shell: |
    export KUBECONFIG={{ kubeconfig }}
    for i in {1..{{ db_instances.user_input }}}
    do
      oc create namespace my-testing-pgbench-ocs-$i
      oc label namespace my-testing-pgbench-ocs-$i "openshift.io/cluster-monitoring=true"
    done
    for i in {1..{{ db_instances.user_input }}}
    do
        oc new-app --name=postgresql-ocs-$i --template=postgresql-persistent-ocs -n my-testing-pgbench-ocs-$i
done
  register: pgbench_instances
  when: db_instances.user_input > 0 and scaling_option.user_input > 0

- debug:
    msg: "Waiting for {{ db_instances.user_input | int * 12 }} seconds"
    
# Pause before starting benchmarking
- name: Waiting for pgbench_instances pods ready
  pause:
    seconds: "{{ db_instances.user_input | int * 12 }}"
