---
- name: Collect the machinesets names
  shell:
            cmd: |
              oc -n {{ machineset_project }} get machinesets -o jsonpath='{range .items[*]}{.metadata.name}{"\n"}{end}' | grep "^cluster"
  register: machinesets

- name: Export the machinesets in yaml files
  shell:
            cmd: |
                    oc -n {{ machineset_project }} get machinesets {{ item }} -o yaml | sed -e 's/{{ item }}/ocs-worker-{{ item.split('-')[5:8] | join('-') }}/g' | sed -e 's/{{ oldinstancetype }}/{{ instancetype }}/g' > ocs-worker-{{ item.split('-')[5:8] | join('-') }}.yaml
  loop: "{{ machinesets.stdout_lines }}"

- name: Configure label in nodes
  lineinfile:
    path: ./ocs-worker-{{ item.split('-')[5:8] | join('-') }}.yaml
    state: absent
    regexp: '^      metadata: {}'
  loop: "{{ machinesets.stdout_lines }}"

- name: delete EBS
  lineinfile:
    path: ./ocs-worker-{{ item.split('-')[5:8] | join('-') }}.yaml
    state: absent
    regexp: '^          - ebs'
  when: not item | string is search ("1c")
  loop: "{{ machinesets.stdout_lines }}"

- name: delete replicas for osd nodes
  lineinfile:
    path: ./ocs-worker-{{ item.split('-')[5:8] | join('-') }}.yaml
    state: absent
    regexp: '^  replicas:'
  when: not item | string is search ("1c")
  loop: "{{ machinesets.stdout_lines }}"

- name: Add deviceName
  lineinfile:
    path: ./ocs-worker-{{ item.split('-')[5:8] | join('-') }}.yaml
    insertafter: '^          blockDevices:'
    line: '          - deviceName: /dev/sdc'
  when: not item | string is search ("1c")
  loop: "{{ machinesets.stdout_lines }}"

- name: replica 2 for OSD nodes
  lineinfile:
    path: ./ocs-worker-{{ item.split('-')[5:8] | join('-') }}.yaml
    insertbefore: '^  selector:'
    line: '  replicas: 2'
  when: not item | string is search ("1c")
  loop: "{{ machinesets.stdout_lines }}"

- name: Add EBS
  lineinfile:
    path: ./ocs-worker-{{ item.split('-')[5:8] | join('-') }}.yaml
    insertafter: '^          - deviceName: /dev/sdc'
    line: '            ebs:'
  when: not item | string is search ("1c")
  loop: "{{ machinesets.stdout_lines }}"

- name: Add EBS size {{ ebs_size }}
  lineinfile:
    path: ./ocs-worker-{{ item.split('-')[5:8] | join('-') }}.yaml
    regexp: '^              volumeSize: .+'
    line: '              volumeSize: {{ ebs_size }}'
  when: not item | string is search ("1c")
  loop: "{{ machinesets.stdout_lines }}"

- name: Add ocs labels to OSD nodes to datacenter1
  blockinfile:
    path: ./ocs-worker-{{ item.split('-')[5:8] | join('-') }}.yaml
    insertbefore: "      providerSpec:"
    block: |2
            taints:
            - effect: NoSchedule
              key: node.ocs.openshift.io/storage
              value: "true"
            metadata:
              creationTimestamp: null
              labels:
                node-role.kubernetes.io/infra: ""
                cluster.ocs.openshift.io/openshift-storage: ""
                topology.kubernetes.io/zones: datacenter1
  when: item | string is search ("1a")
  loop: "{{ machinesets.stdout_lines }}"

- name: Add ocs labels to OSD nodes to datacenter2
  blockinfile:
    path: ./ocs-worker-{{ item.split('-')[5:8] | join('-') }}.yaml
    insertbefore: "      providerSpec:"
    block: |2
            taints:
            - effect: NoSchedule
              key: node.ocs.openshift.io/storage
              value: "true"
            metadata:
              creationTimestamp: null
              labels:
                node-role.kubernetes.io/infra: ""
                cluster.ocs.openshift.io/openshift-storage: ""
                topology.kubernetes.io/zones: datacenter2
  when: item | string is search ("1b")
  loop: "{{ machinesets.stdout_lines }}"

- name: Add ocs labels to arbiter zone
  blockinfile:
    path: ./ocs-worker-{{ item.split('-')[5:8] | join('-') }}.yaml
    insertbefore: "      providerSpec:"
    block: |2
            metadata:
              creationTimestamp: null
              labels:
                node-role.kubernetes.io/infra: ""
                cluster.ocs.openshift.io/openshift-storage: ""
                topology.kubernetes.io/zones: arbiter
  when: item | string is search ("1c")
  loop: "{{ machinesets.stdout_lines }}"

- name: Create machinesets and replicas
  shell:
            cmd: |
                    oc apply -f ocs-worker-{{ item.split('-')[5:8] | join('-') }}.yaml
  loop: "{{ machinesets.stdout_lines }}"

- name: Pause for 5 minutes to provisioning machines
  pause:
    minutes: 5

- name: partitioning disks
  include_tasks: partitioning.yml
  