---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    openshift.io/cluster-monitoring: "true"
  name: testing-ocs-storage
spec: {}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: fio-testing-performance
  name: fio-testing-performance
  namespace: testing-ocs-storage
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: fio-testing-performance
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fio-testing-performance
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: cluster.ocs.openshift.io/testing-ocs-storage
                operator: NotIn
                values:
                - ""
      containers:
      - name: fio-testing-performance
        image: quay.io/cloud-bulldozer/fio:latest
        command:
          - sleep
          - "86400"
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /usr/share/ocs-pvc
          name: test-ocs-pvc
      restartPolicy: Always
      schedulerName: default-scheduler
  volumeClaimTemplates:
  - metadata:
      name: test-ocs-pvc
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 100Gi
      storageClassName: sc-cephrbd-replica2
