---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    openshift.io/cluster-monitoring: "true"
  name: testing-ocs-storage
spec: {}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: fio-file-ceph-tools
  name: fio-file-ceph-tools
  namespace: testing-ocs-storage
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: fio-file-ceph-tools
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fio-file-ceph-tools
    spec:
      containers:
      - name: fio-file-ceph-tools
        image: quay.io/cloud-bulldozer/fio:latest
        command:
          - sleep
          - "86400"
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /usr/share/ocs-pvc
          name: test-ocs-pvc
      restartPolicy: Always
      schedulerName: default-scheduler
  volumeClaimTemplates:
  - metadata:
      name: test-ocs-pvc
    spec:
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 100Gi
      storageClassName: ocs-external-storagecluster-cephfs