---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cephfs-pvc-50
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: ocs-storagecluster-ceph-rbd
