- name: Create the fio statefulset fio-testing-performance accordingly
  shell: |
    export KUBECONFIG={{ kubeconfig }}
    oc create -f roles/rbd_ceph_performance_no_interactive/templates/fio-statefulset.yml
  ignore_errors: yes
- name: Scale fio for OCS to {{ fio_pods }} pods in namespace {{ name_space }}
  shell: |
    export KUBECONFIG={{ kubeconfig }}
    oc -n {{ name_space }} scale statefulset fio-testing-performance --replicas={{ fio_pods }}
  when: fio_pods != ''
  ignore_errors: yes
- name: Waiting for the availability of fio pods={{ fio_pods }}
  shell: |
    export KUBECONFIG={{ kubeconfig }}
    oc -n {{ name_space }} get statefulsets fio-testing-performance -o yaml -o jsonpath='{.items[*]}{@.status.readyReplicas}{"\n"}'
  register: fio_pods_ready
  until: fio_pods_ready.stdout | int == fio_pods | int
  retries: 60
  delay: 10
- shell: |
    export KUBECONFIG={{ kubeconfig }}
    oc -n {{ name_space }} get pods -o wide
  register: fio_pods_print
  when: fio_pods != ''
  ignore_errors: yes
- name: fio pods available in statefulset fio-testing-performance with pvc from storage class {{ storage_class }}
  debug:
    msg: "{{ fio_pods_print.stdout_lines }}"
